repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn",
            "-sn",
            "--rcfile=.pylintrc",
            "--load-plugins=pylint.extensions.docparams",
          ]

      - id: unit-tests
        name: unit tests
        entry: bash -c 'python -m pytest backend/src/tests/unit_tests/ -q --tb=short'
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: requirements
        name: requirements
        entry: bash -c 'venv/bin/pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [pre-commit]
