[pytest]
python_files = test.py tests.py test_*.py tests_*.py *_test.py *_tests.py
asyncio_mode = auto
pythonpath = src

markers =
    unit: mark a test as a unit test.
    integration: mark a test as an integration test.
    functional: mark a test as a functional test.

filterwarnings =
    ignore::DeprecationWarning:testcontainers.*
    