export const loginPageStyles = {
  layout: "min-h-screen bg-white flex justify-start flex-col gap-6 items-center justify-center",
  form: "grid w-full max-w-sm grid-cols-1 gap-2",
  logoWrapper: "flex items-center justify-center h-50 w-full mt-15",
  logo: "h-80 w-auto object-contain justify-self-center",
  heading: "text-2xl font-semibold text-gray-900 text-center",
  fieldWrapper: "flex flex-col gap-3", 
  formLabel: "mb-1 text-sm font-medium text-gray-700",
  label: "text-base font-medium text-gray-700",
  input: "w-full border border-gray-300 rounded-lg px-3 py-2 text-base bg-white focus:outline-none focus:ring-2 focus:ring-gray-400 transition",
  row: "flex items-center justify-between",
  checkboxWrapper: "flex items-center gap-2",
  checkbox: "w-4 h-4 accent-gray-800",
  checkboxLabel: "text-base text-gray-600",
  forgotLink: "text-base text-gray-800 hover:underline font-semibold",
  button: "w-full bg-zinc-950 text-white py-3 rounded-lg hover:bg-zinc-800 transition-colors font-semibold text-base disabled:opacity-50 disabled:cursor-not-allowed",
  error: "text-red-500 text-sm",
  bottomText: "text-base text-gray-500 text-center",
  signupLink: "text-gray-900 font-semibold hover:underline",
}