export const loginPageStyles = {
  layout: "min-h-screen bg-white flex ml-5 mr-5 justify-start flex-col gap-6 items-center justify-center",
  form: "grid w-full max-w-sm grid-cols-1 gap-2",
  logoWrapper: "flex items-center justify-center ",
  logo: "h-60 w-auto object-contain justify-self-center",
  heading: "text-lg font-semibold text-gray-900 text-center -mt-8",
  fieldWrapper: "flex flex-col gap-1", 
  formLabel: "text-sm font-medium text-gray-700",
  label: "text-sm font-medium text-gray-700 ",
  input: "w-full border border-gray-300 rounded-lg py-2 px-4 text-base bg-white focus:outline-none focus:ring-2 focus:ring-gray-400 transition",
  passwordWrapper: "relative flex items-center",
  passwordInput: "w-full border border-gray-300 rounded-lg py-2 px-4 pr-10 text-base bg-white focus:outline-none focus:ring-2 focus:ring-gray-400 transition",
  eyeBtn: "absolute right-3 text-gray-400 hover:text-gray-600 transition-colors",
  eyeIcon: "w-5 h-5",
  row: "flex items-center justify-between",
  checkboxWrapper: "flex items-center gap-2",
  checkbox: "w-4 h-4 accent-gray-800",
  checkboxLabel: "text-sm text-gray-600",
  forgotLink: "text-sm text-gray-800 hover:underline font-semibold",
  button: "w-full bg-zinc-950 text-white text-sm py-3 rounded-lg hover:bg-zinc-800 transition-colors font-semibold text-base disabled:opacity-50 disabled:cursor-not-allowed",
  error: "text-red-500 text-sm",
  bottomText: "text-sm text-gray-500 text-center",
  signupLink: "text-gray-900 font-semibold hover:underline",
}